import Head from "next/head";
import Header from "../components/Header";
import styled from "styled-components";
import CreateTopic from "../components/CreateTopic";

function createtopic() {
  return (
    <Container>
      <Head>
        <title>Create Topic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />

      {/* Main Body */}
      <MainBody>
        <div className="createPostContent">
          <CreateTopic />
        </div>
      </MainBody>

      {/* Footer */}
    </Container>
  );
}

export default createtopic;

const Container = styled.div`
  background-color: #f6f7f9;
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  width: 100%;
`;

const MainBody = styled.div`
  display: flex;
  flex-direction: column;
  text-align: center;
  margin-top: 6rem;
  @media only screen and (min-width: 768px) {
    margin-top: 7rem;
  }
  @media only screen and (min-width: 1280px) {
    margin-top: 8rem;
  }
  .createPostContent {
    background-color: white;
    padding: 1rem;
    margin: 0 30vw;
    @media only screen and (max-width: 640px) {
      margin: 0 10vw;
    }
    @media only screen and (min-width: 640px) {
      align-self: center;
      width: 32rem;
    }
    @media only screen and (min-width: 1024px) {
      width: 60vw;
    }
    @media only screen and (min-width: 1280px) {
      width: 49rem;
    }
    height: 60vh;
    border-radius: 5px;
    --tw-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1),
      0 10px 10px -5px rgba(0, 0, 0, 0.04);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000),
      var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
    font-family: "Source Sans Pro", sans-serif;

    form {
      display: flex;
      flex-direction: column;
    }
  }
`;
