import Head from "next/head";
import Header from "../components/Header";
import styled from "styled-components";
import MainBody from "../components/MainBody";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap');
        </style>
      </Head>
      {/* Header */}
      <Header />

      {/* Main Body */}
      <MainBody />

      {/* Footer */}
    </Container>
  );
}

const Container = styled.div`
  background-color: #f6f7f9;
  display: flex;
  flex-direction: column;
  min-height: 100vh;
  width: 100%;
`;
